version: '3.9'

services:
  demo.publisher.api:
    image: ${DOCKER_REGISTRY-}demopublisherapi
    build:
      context: .
      dockerfile: Demo.Publisher.API/Dockerfile
    environment:
     - ASPNETCORE_URLS=http://+:80
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8080:80"
    restart: always
    depends_on:
     - "rabbitmq"
  demo.subscriber.console:
    image: ${DOCKER_REGISTRY-}demosubscriberconsole
    build:
      context: .
      dockerfile: Demo.Subscriber.Console/Dockerfile
    restart: always
    depends_on:
     - "rabbitmq"
     - "demo.publisher.api"
  rabbitmq: # login guest:guest
    image: rabbitmq:management-alpine
    hostname: "rabbitmq"
    labels:
     name: "rabbitmq"
    container_name: "rabbitmq"    
    ports:
     - 5672:5672
     - 15672:15672